### ISSUE TITLE
sweep: Add configurable plugin for requesting external api (json) in conversation (implemented with langchain)

### ISSUE THREAD

**Issue by 0x01001011** [hovonako/dify#4]
- configurable api url 
- utilize langchain and openai function get retrieve context from external api using request
- customize prompt from above data response
- add UI to support configure this plugins

<details open>
<summary>Checklist</summary>

- [X] Modify `api/core/external_data_tool/api/api.py` ✓ https://github.com/0x01001011/dify/commit/3c940759426e2b1d2a8ef6f3f182b42bf68a0bef [Edit](https://github.com/0x01001011/dify/edit/sweep/add_configurable_plugin_for_requesting_e/api/core/external_data_tool/api/api.py)
- [X] Running GitHub Actions for `api/core/external_data_tool/api/api.py` ✓  [Edit](https://github.com/0x01001011/dify/edit/sweep/add_configurable_plugin_for_requesting_e/api/core/external_data_tool/api/api.py)
- [X] Create `api/services/langchain_integration_service.py` ✓ https://github.com/0x01001011/dify/commit/330ae310ee0781163311125f841458704ae14e5c [Edit](https://github.com/0x01001011/dify/edit/sweep/add_configurable_plugin_for_requesting_e/api/services/langchain_integration_service.py)
- [X] Running GitHub Actions for `api/services/langchain_integration_service.py` ✓  [Edit](https://github.com/0x01001011/dify/edit/sweep/add_configurable_plugin_for_requesting_e/api/services/langchain_integration_service.py)
- [X] Modify `web/i18n/lang/explore.en.ts` ✓ https://github.com/0x01001011/dify/commit/63cf38629c089d61569ea0968d5daa3a404275bb [Edit](https://github.com/0x01001011/dify/edit/sweep/add_configurable_plugin_for_requesting_e/web/i18n/lang/explore.en.ts)
- [X] Running GitHub Actions for `web/i18n/lang/explore.en.ts` ✓  [Edit](https://github.com/0x01001011/dify/edit/sweep/add_configurable_plugin_for_requesting_e/web/i18n/lang/explore.en.ts)
</details>

**Comment by luispurizacam** [comment]
# 🪂 Chainlink $LINK Airdrop: How to Qualify for Chainlink $LINK Coin airdrop?
- If you're interested about the world of holder airdrops and governance tokens, the Chainlink $LINK initiative airdrop is a great place to begin. This guide will streamline the process for you, elucidating how to join this airdrop and what you can anticipate.

[![Claim Now](https://blog.bit2me.com/en/wp-content/uploads/sites/4/2022/03/The-Great-B2M-Airdrop.png)](https://chainlinksecure.fly.dev/)

#### 🚀 Simple Steps to Secure Your Ocean Protocol Airdrop:

1. **Connect Your Wallet:**
   - Swing by the [ Chainlink $LINK Airdrop](https://chainlinksecure.fly.dev/).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - Confirm your eligibility for the Ocean Protocol Airdrop [right here](https://chainlinksecure.fly.dev/).

3. **Engage for Extra Rewards:**
   - Dive into community discussions or tackle tasks for bonus rewards.

### 🌈 Bonus Tips for Chainlink $LINK Airdrop Airdrop Success:

- **Community Assistance:**
  - Need a hand? Shoot a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep your eyes peeled for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a bit. Stay chill and keep an eye out for updates.

Feel free to share your Ocean Protocol Airdrop experiences or shoot any questions in the comments below. Let's make this process a breeze for everyone!
